#                                                           Developed by Sxntido
#                                                     (Aquatic Studios @ (C) 2019-2023)

name: 'Aquafly'
version: '3.0'
api-version: 1.13
authors:
  - 'Sxntido'

main: team.aquatic.studios.Aquafly
website: https://github.com/aquaticstudios/Aquafly
description: 'All rights reserved by Aquatic Studios'

commands:
  fly:
    description: Command to run flight mode
    aliases: [flight, flyaqua]
  aquafly:
    description: Use command for flight mode